---
- name: Update System Packages
  hosts: all
  become: yes  

  tasks:
    - name: Update using APT (Debian/Ubuntu)
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Update using YUM (RHEL/CentOS)
      yum:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == 'yum'

    - name: Update using Pacman (Arch Linux)
      pacman:
        update: yes
        upgrade: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Update using Pamac (Manjaro)
      community.general.pamac:
        update: yes
      when: ansible_pkg_mgr == 'pamac'

    - name: Update using Snap (Snapd)
      community.general.snap:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == 'snap'
