---
downloads: ~/.ansible-downloads/

latte_github_template: https://raw.githubusercontent.com/Cuupa/ansible-playbooks/main/files/arch/latte-dock/Default.layout.latte
latte_config_folder: ~/.config/latte/templates

configure_dotfiles: false
configure_terminal: false

homebrew: false

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

pacman_installed_packages:
  # - ansible # Installed via Pip.
  - atom
  - bash-completion
  - camunda-modeler
  - davfs2
  - discord
  - docker
  - google-chrome
  - gufw
  - jdk-openjdk
  - handbrake
  - htop
  - ffmpeg
  - filelight
  - git
  - htop
  - latte-dock
  - sqlite
  - maven
  - nano
  - nmap
  - obs-studio
  - openssl
  - piper
  - spotify
  - steam-manjaro
  - synology-drive-client
  - virtualbox
  - vlc
  - wget

pacman_uninstalled_packages:
    - audacity
    - etcher
    - fbida
    - guetzli
    - kdeconnect
    - scenarist
    - tomcat9
    - yubikey-manager
    - yubikey-personalization

pamac_installed_packages:
  - 1password

snap_installed_packages:
  - Czkawka
