---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

pacman_installed_packages:
  # - ansible # Installed via Pip.
  - 1password
  - atom
  - bash-completion
  - camunda-modeler
  - davfs2
  - discord
  - docker
  - google-chrome
  - handbrake
  - htop
  - ffmpeg
  - git
  - htop
  - latte-dock
  - sqlite
  - maven
  - nano
  - nmap
  - ssh-copy-id
  - obs-studio
  - openssl
  - spotify
  - steam-manjaro
  - synology-drive-client
  - vlc
  - wget
