---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

homebrew: true

jetbrains_path: /Users/simon/Library/Application\ Support/JetBrains/Toolbox/apps/

dockutil_install_path: /usr/local/bin/dockutil

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  # - Messages
  # Need to be localized ..
  - Nachrichten
  - Mail
  - Karten
  - FaceTime
  - Kalender
  - Kontakte
  - Safari
# - 'App Store'
dockitems_persist:
  - name: "Terminal"
    path: "/System/Applications/Utilities/Terminal.app"
    pos: 2
  - name: "1Password"
    path: "/Applications/1Password 7.app/"
    pos: 3
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 4
  - name: "Screenshot"
    path: "/System/Applications/Utilities/Screenshot.app"
    pos: 5
  - name: "Atom"
    path: "/Applications/Atom.app"
    pos: 6
  - name: "Camunda Modeler"
    path: "/Applications/Camunda Modeler.app"
    pos: 7
  - name: "Cyberduck"
    path: "/Applications/Cyberduck.app"
    pos: 8
  - name: "Discord"
    path: "/Applications/Discord.app"
    pos: 9
  - name: "Spotify"
    path: "/Applications/Spotify.app"
    pos: 10
  - name: "Steam"
    path: "/Applications/Steam.app"
    pos: 11
  - name: "OBS"
    path: "/Applications/OBS.app"
    pos: 12
  - name: "Fotos"
    path: "/System/Applications/Photos.app"
    pos: 13
  - name: "Erinnerungen"
    path: "/System/Applications/Reminders.app"
    pos: 14
  - name: "Notizen"
    path: "/System/Applications/Notes.app"
    pos: 14
  - name: "Musik"
    path: "/System/Applications/Music.app"
    pos: 15
  - name: "App Store"
    path: "/System/Applications/App Store.app"
    pos: 16
  - name: "OpenVPN Connect"
    path: "/Applications/OpenVPN Connect.app"
    pos: 17
  - name: "Systemeinstellungen"
    path: "/System/Applications/System Preferences.app"
    pos: 18

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - docker
  - ffmpeg
  - git
  - htop
  - sqlite
  - maven
  - nano
  - nmap
  - ssh-copy-id
  - openssl
  - openjdk
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - atom
  - caffeine
  - camunda-modeler
  - cyberduck
  - chromedriver
  - discord
  - google-chrome
  - handbrake
  - jetbrains-toolbox
  - obs
  - openvpn-connect
  - spotify
  - steam
  - virtualbox
  - vlc

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

composer_packages: []
