---
- name: Ensure Atom is installed - Archlinux
  become: yes
  pacman:
    name: atom
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

- name: Ensure Atom is installed - Darwin
  become: yes
  homebrew_cask:
    name: atom
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: "Install atom.io Packages"
  ansible.builtin.include_tasks: atom-add.yml
  loop: "{{ atom_installed_packages }}"