- name: Create temporary download directory
  ansible.builtin.file:
    path: "{{ downloads }}"
    state: directory

- name: Download Latte template.
  ansible.builtin.get_url:
    url: {{ latte_github_template }}
    dest: "{{ downloads }}"

- name: Configure Latte-Dock
  ansible.builtin.command:
<<<<<<< HEAD
    cmd: "latte-dock --import-layout {{ downloads }}Default.layout.latte"
=======
    cmd: "cp {{ downloads }}/Default.layout.latte {{ latte_config_folder }}"
>>>>>>> refs/remotes/origin/main
