- name: Create temporary download directory.
  ansible.builtin.file:
    path: "{{ downloads }}"
    state: directory

- name: Download Latte template.
  ansible.builtin.get_url:
    url: {{ latte_github_template }}
    dest: "{{ downloads }}"

- name: Configure Latte-Dock.
  ansible.builtin.command:
    cmd: "cp {{ downloads }}/Default.layout.latte {{ latte_config_folder }}"

- name: Download Iconpack.
  ansible.builtin.get_url:
    url: {{ plasma_icons_github }}
    dest: "{{ downloads }}"

- name: Extract Icons to folder.
  ansible.builtin.unarchive:
    src: {{ downloads }}Mkos-Big-Sur.tar.xz
    dest: {{ plasma_icons_folder }}

- name: Configure Plasma-icons.
  ansible.builtin.command:
    cmd: "/usr/lib/plasma-changeicons Mkos-big-sur"

- name: Download Plasma-theme.
  ansible.builtin.get_url:
    url: {{ plasma_theme_github }}
    dest: "{{ downloads }}"

- name: Extract Theme to folder.
  ansible.builtin.unarchive:
    src: {{downloads }}McMojave.tar.gz
    dest: {{ plasma_theme_folder }}

- name: Set theme.
  ansible.builtin.command:
    cmd: "/usr/bin/lookandfeeltool -a {{ plasma_theme_folder }}com.github.vinceliuice.McMojave"

- name: Restart Plasmashell
  ansible.builtin.command:
   cmd: "kquitapp5 plasmashell || killall plasmashell && kstart5 plasmashell"
