---
mas_email: ""
mas_password: ""
mas_uninstalled_apps: []
mas_installed_app_ids: []  # Deprecated
mas_installed_apps:
  - {id: 497799835, name: "Xcode (8.1)"}
mas_upgrade_all_apps: false
mas_signin_dialog: false
